import { FormEvent, useEffect, useState } from "react";
import { useLocation } from "wouter";
import { BookOpenCheck, FileText, KeyRound, LayoutDashboard, LogOut, MonitorX, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useIsMobile } from "@/hooks/useMobile";
import { trpc } from "@/lib/trpc";

const menuItems = [
  { icon: LayoutDashboard, label: "Overview", path: "/admin" },
  { icon: FileText, label: "Requests", path: "/admin/requests" },
  { icon: BookOpenCheck, label: "Knowledge base", path: "/admin/knowledge" },
  { icon: Settings2, label: "Topics & areas", path: "/admin/topics" },
  { icon: KeyRound, label: "Account", path: "/admin/account" },
];

type Mode = "login" | "register" | "forgot" | "reset";
type AdminIdentity = { id: number; email: string; collegeId: number; collegeName: string; collegeCode: string };

function AccessCard() {
  const [, navigate] = useLocation(); const utils = trpc.useUtils(); const [mode, setMode] = useState<Mode>(() => new URLSearchParams(window.location.search).get("reset") ? "reset" : "login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [collegeName, setCollegeName] = useState(""); const resetToken = new URLSearchParams(window.location.search).get("reset") ?? "";
  const signedIn = () => { utils.adminAuth.me.invalidate(); navigate("/admin"); };
  const login = trpc.adminAuth.login.useMutation({ onSuccess: signedIn, onError: error => toast.error(error.message) });
  const register = trpc.adminAuth.register.useMutation({ onSuccess: result => { toast.success(`Campus created. Your college code is ${result.college.code}.`); signedIn(); }, onError: error => toast.error(error.message) });
  const forgot = trpc.adminAuth.forgotPassword.useMutation({ onSuccess: () => toast.success("If an account uses this email, a reset link will be sent."), onError: error => toast.error(error.message) });
  const reset = trpc.adminAuth.resetPassword.useMutation({ onSuccess: () => { toast.success("Password reset. You are now signed in."); signedIn(); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); if ((mode === "register" || mode === "reset") && password !== confirmPassword) return toast.error("Passwords do not match."); if (mode === "login") login.mutate({ email, password }); if (mode === "register") register.mutate({ collegeName, email, password }); if (mode === "forgot") forgot.mutate({ email }); if (mode === "reset") reset.mutate({ token: resetToken, password }); };
  const title = mode === "register" ? "Create administrator account" : mode === "forgot" ? "Reset your password" : mode === "reset" ? "Choose a new password" : "Run as administrator";
  const caption = mode === "register" ? "Create the first private administrator account for your college." : mode === "forgot" ? "Enter your registered administrator email to receive a reset link." : mode === "reset" ? "Set a new password for your private administrator account." : "Sign in to manage your college’s support content and requests.";
  return <div className="min-h-screen bg-[#f7f6f2] px-5 py-12"><div className="mx-auto w-full max-w-md rounded-3xl border border-[#102a43]/10 bg-white p-7 shadow-[0_24px_60px_-38px_rgba(16,42,67,.55)] sm:p-9"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#102a43] text-[#e8c569]"><BookOpenCheck className="h-6 w-6"/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-[#b8891d]">Private campus workspace</p><h1 className="mt-2 font-serif text-3xl font-semibold tracking-tight text-[#102a43]">{title}</h1><p className="mt-3 text-sm leading-6 text-[#5c7590]">{caption}</p><form onSubmit={submit} className="mt-7 grid gap-4">{mode === "register" && <div><Label htmlFor="collegeName" className="mb-2 block">College name</Label><Input id="collegeName" value={collegeName} onChange={e => setCollegeName(e.target.value)} required placeholder="e.g. Riverside College"/></div>}{mode !== "reset" && <div><Label htmlFor="adminEmail" className="mb-2 block">Registered email</Label><Input id="adminEmail" type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="admin@college.edu"/></div>}{mode !== "forgot" && <div><Label htmlFor="adminPassword" className="mb-2 block">{mode === "reset" ? "New password" : "Password"}</Label><Input id="adminPassword" type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={8} autoComplete={mode === "login" ? "current-password" : "new-password"}/><p className="mt-1 text-xs text-[#7e97aa]">Use at least 8 characters with a letter and a number.</p></div>}{(mode === "register" || mode === "reset") && <div><Label htmlFor="confirmPassword" className="mb-2 block">Confirm new password</Label><Input id="confirmPassword" type="password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} required minLength={8} autoComplete="new-password"/></div>}<Button type="submit" disabled={login.isPending || register.isPending || forgot.isPending || reset.isPending} className="mt-2 bg-[#102a43] text-white hover:bg-[#163b5c]">{mode === "login" ? "Sign in securely" : mode === "register" ? "Create administrator account" : mode === "forgot" ? "Send reset link" : "Reset password"}</Button></form><div className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-sm"><button type="button" onClick={() => setMode("login")} className="font-semibold text-[#102a43] hover:text-[#b8891d]">Sign in</button><button type="button" onClick={() => setMode("register")} className="font-semibold text-[#102a43] hover:text-[#b8891d]">Create account</button><button type="button" onClick={() => setMode("forgot")} className="font-semibold text-[#102a43] hover:text-[#b8891d]">Forgot password?</button></div></div></div>;
}

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const isMobile = useIsMobile(); const { data: admin, isLoading } = trpc.adminAuth.me.useQuery();
  if (isMobile) return <div className="grid min-h-screen place-items-center bg-[#f7f6f2] p-6 text-center"><div className="max-w-md rounded-3xl border border-[#102a43]/10 bg-white p-8 shadow-[0_20px_55px_-36px_rgba(16,42,67,.5)]"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#102a43] text-[#e8c569]"><MonitorX className="h-7 w-7"/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-[#b8891d]">Desktop workspace</p><h1 className="mt-2 font-serif text-3xl font-semibold text-[#102a43]">Administrator access is available on a laptop or PC.</h1><p className="mt-4 text-sm leading-6 text-[#5c7590]">For the security and clarity of campus management tasks, this workspace is not available on phones or tablets. Please continue from a desktop browser.</p></div></div>;
  if (isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f6f2]"><div className="h-8 w-8 animate-spin rounded-full border-2 border-[#b8891d] border-t-transparent"/></div>;
  if (!admin) return <AccessCard />;
  return <Workspace admin={admin}>{children}</Workspace>;
}

function Workspace({ admin, children }: { admin: AdminIdentity; children: React.ReactNode }) {
  const [location, navigate] = useLocation(); const utils = trpc.useUtils(); const logout = trpc.adminAuth.logout.useMutation({ onSuccess: () => { utils.adminAuth.me.invalidate(); navigate("/"); } }); const active = menuItems.find(item => item.path === location) ?? menuItems[0];
  return <div className="min-h-screen bg-[#f7f6f2] lg:grid lg:grid-cols-[248px_1fr]"><aside className="flex min-h-screen flex-col bg-[#102a43] p-4 text-white"><div className="flex items-center gap-3 border-b border-white/10 px-2 pb-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/10 text-[#e8c569]"><BookOpenCheck className="h-5 w-5"/></span><div><p className="font-serif font-semibold">Campus Helpdesk</p><p className="mt-0.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#a6b9c8]">Administration</p></div></div><nav className="mt-6 grid gap-1">{menuItems.map(item => <button type="button" key={item.path} onClick={() => navigate(item.path)} className={`flex h-10 items-center gap-3 rounded-lg px-3 text-left text-sm font-medium transition-colors ${location === item.path ? "bg-[#e8c569] text-[#102a43]" : "text-white/70 hover:bg-white/10 hover:text-white"}`}><item.icon className="h-4 w-4"/>{item.label}</button>)}</nav><div className="mt-auto border-t border-white/10 pt-4"><p className="px-2 text-sm font-semibold">{admin.collegeName}</p><p className="mt-1 px-2 text-xs text-white/55">{admin.email}</p><button type="button" onClick={() => logout.mutate()} className="mt-4 flex h-10 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium text-white/70 hover:bg-white/10 hover:text-white"><LogOut className="h-4 w-4"/>Log out</button></div></aside><div><header className="flex h-[76px] items-center justify-between border-b border-[#102a43]/10 bg-[#f7f6f2]/90 px-8 backdrop-blur"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b8891d]">{admin.collegeName}</p><h1 className="mt-0.5 font-serif text-xl font-semibold text-[#102a43]">{active.label}</h1></div><span className="inline-flex items-center gap-2 text-xs font-semibold text-[#5c7590]"><span className="h-2 w-2 rounded-full bg-[#5b9279]"/>Private session active</span></header><main className="min-h-[calc(100vh-76px)] p-8">{children}</main></div></div>;
}
